### ISSUE TITLE
Ошибки компиляции

### ISSUE THREAD

**Issue by dragrayraptor** [speedy-hackathon/third-app#11]
в Person.cs 23 строчка: 
home = new Rectangle(homeCoords.X, homeCoords.Y, HouseCoordinates.Width, HouseCoordinates.Height);
не объявлена переменная или поле home
В Game.cs 49 строчка
person.IsInfected = true
Там надо IsSick походу вместо IsInfected

**Comment by Aminopyridin** [comment]
Какая команда? Чтобы балл начислить

**Comment by dragrayraptor** [comment]
Команда 6

**Comment by dragrayraptor** [comment]
> Какая команда? Чтобы балл начислить

Команда 6

**Comment by Aminopyridin** [comment]
Фиксите и шлите ПР

**Comment by dragrayraptor** [comment]
> Фиксите и шлите ПР

Отправил

**Comment by Aminopyridin** [comment]
И получил 2 балла)
